In [5]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [10]:
# Creating a Numpy Array
lst = [1.5, "string", True, 4]

arr = np.array(lst)
print(arr)

['1.5' 'string' 'True' '4']


In [12]:
# .dtype attribute
print(arr.dtype)

<U32


In [18]:
"""
Size Comparison of ndarray and list objects
"""
from sys import getsizeof

lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
print(getsizeof(lst))

arr = np.array(lst)
print(getsizeof(arr))

192
172


In [20]:
"""
Operations with Numpy Arrays
"""
prices = [30, 25, 40, 20, 20, 35, 50, 35]

# list
new_prices = [price-5 for price in prices]
print(new_prices)

# numpy array
prices_arr = np.array(prices)
prices_arr = prices_arr - 5
print(prices_arr)

[25, 20, 35, 15, 15, 30, 45, 30]
[25 20 35 15 15 30 45 30]


In [48]:
"""
실습 문제 : 시험 점수 처리
"""
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

test_3_fixed = test_3 + 2

total_grade = test_1 + test_2 + test_3_fixed
print(total_grade)

final_grade = total_grade / 3
print(final_grade)

jeremy_test_2 = test_2[3]
print(jeremy_test_2)

manual_adwoa_test_1 = np.array([test_1[1], test_1[2]])
print(manual_adwoa_test_1)

student_scores = np.array([test_1, test_2, test_3_fixed])
print(student_scores)

print(student_scores[2][0])

print(student_scores[:, 4])

[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]
93
[94 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 89  87  74  92  94]]
89
[87 91 94]


In [54]:
"""
Logical Operations with Arrays
"""
#masking
a = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
mask = a > 5
print(mask)

# select using Logical operation
selected = a[a > 5]
print(selected)

# combined Logical operations | &
selected = a[(a > 6) | (a < 4)]
print(selected)

[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  3  9  8  9  7]


In [57]:
"""
실습 문제 : 골디락스 포리지(죽) 페스티벌
"""
porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])

cold = porridge[porridge <= 50]
hot = porridge[porridge > 50]

print(cold)
print(hot)

[50]
[79 65 63 56 90 85 98 79 51]
