In [3]:
import numpy as np

In [5]:
"""
Numpy Array Attributes
"""
# Creating an array
print(np.arange(3))

[0 1 2]


In [26]:
# Random number generation

np.random.seed(0)
arr1 = np.random.randint(10, size = 6)
print(arr1)
arr2 = np.random.randint(10, size = (3, 4))
print(arr2)
arr3 = np.random.randint(10, size = (3, 4, 5))
print(arr3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [32]:
# Attributes
print(arr2)

print("arr2.ndim = ", arr2.ndim)
print("arr2.shape = ", arr2.shape)
print("arr2.size = ", arr2.size)
print("arr2.dtype = ", arr2.dtype)
print("arr2.itemsize = ", arr2.itemsize)
print("arr2.nbytes = ", arr2.nbytes)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
arr2.ndim =  2
arr2.shape =  (3, 4)
arr2.size =  12
arr2.dtype =  int32
arr2.itemsize =  4
arr2.nbytes =  48


In [37]:
"""
Slicing
"""
arr = np.arange(10)
print(arr)

print(arr[3:7])
print(arr[5:])
print(arr[:5])

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[5 6 7 8 9]
[0 1 2 3 4]


In [49]:
# Multi-dimensional Subarrays
np.random.seed(0)
arr = np.random.randint(10, size = (3, 4))
print(arr)
print(arr[0:2, 0:2])

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[[5 0]
 [7 9]]


In [56]:
"""
Subarrays an no-copy views
"""
np.random.seed(0)
arr = np.random.randint(10, size = (3, 4))
print(arr, "\n")
arr_sub = arr[0, 0] = 99
print(arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

[[99  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]


In [63]:
# .copy()
arr_sub = arr[0 : 1, 0 : 1].copy()
print(arr)
print(arr_sub)
arr_sub = [1]
print(arr)
print(arr_sub)

[[99  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]
[[99]]
[[99  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]
[1]


In [87]:
"""
Reshaping of array
"""
np.random.seed(0)
arr = np.random.randint(10, size = 12)
print(arr)
arr = arr.reshape(3, 4)
print(arr)

[5 0 3 3 7 9 3 5 2 4 7 6]
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [84]:
# np.newaxis
np.random.seed(0)
arr = np.random.randint(10, size = 3)
print(arr)
arr_new = arr[: , np.newaxis]
print(arr_new)

[5 0 3]
[[5]
 [0]
 [3]]


In [71]:
"""
Array Concatenation
"""
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
arr_3 = np.array([7, 8, 9])

arr_total = np.concatenate([arr_1, arr_2, arr_3])
print(arr_total)

[1 2 3 4 5 6 7 8 9]


In [73]:
"""
Array Splittng
"""
arr = [1, 2, 3, 4, 5, 6, 7]
print(arr)
arr_1, arr_2, arr_3 = np.split(arr, [2, 5])
print(arr_1)
print(arr_2)
print(arr_3)

[1, 2, 3, 4, 5, 6, 7]
[1 2]
[3 4 5]
[6 7]
