In [5]:
import numpy as np

In [15]:
"""
numpy.ufunc
"""
np.random.seed(1)
arr1 = np.random.randint(10, size = 5)
arr2 = np.random.randint(10, size = 5)
print(arr1, arr2)

arr1 = arr1 - 2
print(arr1, arr2)

arr3 = arr1 + arr2
print(arr3)

arr4 = np.random.randint(10, size = (3, 5))
print(arr4)

arr5 = arr4 ** 2
print(arr5)

[5 8 9 5 0] [0 1 7 6 9]
[ 3  6  7  3 -2] [0 1 7 6 9]
[ 3  7 14  9  7]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [20]:
"""
ufuncs : Absolute Value
"""
x = np.array([-2, -1, 0, 1, 2])
print(np.abs(x))

x = np.array([3-4j])
print(np.abs(x))

[2 1 0 1 2]
[5.]


In [29]:
"""
ufuncs : Trigonometric functions
"""
theta = np.linspace(0, np.pi, 3)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

x = np.linspace(0, 100, 11)
print(x)

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [34]:
"""
ufuncs : aggregation
"""
x = np.arange(1, 5)
print(x)
aggr = np.add.reduce(x)
print(aggr)
aggr = np.multiply.reduce(x)
print(aggr)

[1 2 3 4]
10
24


In [37]:
# accumulate()
print(x)

accum = np.add.accumulate(x)
print(accum)
accum = np.multiply.accumulate(x)
print(accum)

[1 2 3 4]
[ 1  3  6 10]
[ 1  2  6 24]


In [40]:
# summing the value in an array
np.random.seed(3)
arr = np.random.rand(1000000) # rand(): cearte 0~1 real numbers

print(arr)
print("sum = ", np.sum(arr))

[0.5507979  0.70814782 0.29090474 ... 0.93033748 0.80429816 0.47400579]
sum =  500422.19897015305


In [43]:
%timeit sum(arr)

72.8 ms ± 637 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [45]:
%timeit np.sum(arr)

1.12 ms ± 14.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [50]:
# other aggr function

print("max = ", np.max(arr))
print("min = ", np.min(arr))
print("mean = ", np.mean(arr))
print("median = ", np.median(arr))
print("percentile = ", np.percentile(arr, 90))
print(np.any(arr>1))
print(np.all(arr<1))

max =  0.9999996367889004
min =  1.5496004267534502e-06
mean =  0.500422198970153
median =  0.5005659265960778
percentile =  0.9001765340710965
False
True


In [52]:
# multi dimensional aggregates
np.random.seed(5)
arr = np.random.randint(10, size = (3, 5))
print(arr)
arr1 = np.sum(arr, axis = 0)
print(arr1)
arr2 = np.sum(arr, axis = 1)
print(arr2)

[[3 6 6 0 9]
 [8 4 7 0 0]
 [7 1 5 7 0]]
[18 11 18  7  9]
[24 19 20]
