In [62]:
import numpy as np

In [9]:
"""
Introduction to Broadcasting
"""
x = np.ones((3, 3))
print(x)
y = np.arange(3)
print(y)
print(x + y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [14]:
"""
broadcasting both arrays
"""
a = np.arange(3)
print(a)
a = a[ : , np.newaxis]
print(a)
b = np.arange(3)
print(b)
print(a + b)

[0 1 2]
[[0]
 [1]
 [2]]
[0 1 2]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [19]:
"""
Broadcasting Rules
"""
a = np.ones((2, 3))
print(a)
b = np.arange(3)
print(b)

print(a + b)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]]


In [24]:
"""
Comparisons, Masks, asd Boolean Logic
"""
x = np.array([1, 2, 3, 4, 5])
print(x)

print(x < 3)
print(x >= 3)
print(x != 3)
print(x == 3)

[1 2 3 4 5]
[ True  True False False False]
[False False  True  True  True]
[ True  True False  True  True]
[False False  True False False]


In [26]:
"""
bool masking fo multi=dimensional arrays
"""
np.random.seed(0)
x = np.random.randint(10, size = (3, 4))
print(x) 
print(x < 6)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[[ True  True  True  True]
 [False False  True  True]
 [ True  True False False]]


In [32]:
"""
Working wuth Boolean Arrays
"""
print(x)
print(np.count_nonzero(x < 6))
print(np.sum(x < 6))
print(np.any(x > 8))
print(np.all(x < 5))

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
8
8
True
False


In [38]:
"""
Mask Operation
"""
print(x < 5)
print(x[x < 5])
print(np.mean(x[x < 5]))

[[False  True  True  True]
 [False False  True False]
 [ True  True False False]]
[0 3 3 3 2 4]
2.5


In [44]:
"""
Fancy Indexing
"""  
np.random.seed(1)
x = np.random.randint(100, size = 10)
print(x)
print(x[2], x[4], x[6])

ind = [2, 4, 6]
print(x[ind])

[37 12 72  9 75  5 79 64 16  1]
72 75 79
[72 75 79]


In [46]:
"""
for n-d array
"""
np.random.seed(2)
x = np.random.randint(10, size = (3, 5))
print(x)

row = [0, 1, 2]
col = [1, 3, 2]
print(x[row, col])

[[8 8 6 2 8]
 [7 2 1 5 4]
 [4 5 7 3 6]]
[8 5 7]


In [49]:
"""
for n-d array with broadcasting
"""
print(x)
row = np.array([0, 1, 2])
col = np.array([2, 1, 4])
 
print(x[row[:, np.newaxis], col])

[[8 8 6 2 8]
 [7 2 1 5 4]
 [4 5 7 3 6]]
[[6 8 8]
 [1 2 4]
 [7 5 6]]


In [56]:
"""
combined indexing
"""
x = np.arange(1, 13).reshape(3, 4)
print(x)

print(x[2, [2, 0, 1]])
print(x[1:, [2, 0, 1]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[11  9 10]
[[ 7  5  6]
 [11  9 10]]


In [61]:
"""
Example : Selecting random points
"""
mean = [0, 0]
cov = [[1, 2], [2, 5]]

rand = np.random.RandomState(1)
x = rand.multivariate_normal(mean, cov, 100)
print(x)
print(x.shape)

[[-1.26659039e+00 -3.71998007e+00]
 [ 8.98574387e-01  1.00797760e+00]
 [ 8.12283322e-02 -2.29506499e+00]
 [-1.32069461e+00 -4.01236325e+00]
 [-1.99323780e-01 -7.51126722e-01]
 [-5.62429879e-01 -3.58770608e+00]
 [ 4.44845894e-01  6.58255553e-01]
 [-6.26556217e-01 -2.70315425e+00]
 [ 4.95244764e-01  2.45439522e-01]
 [-2.62034143e-01 -1.77174030e-03]]
(10, 2)
